(function(){
  'use strict';
  var EN={
    'À propos':'About','Dossiers':'Services','Auto-diagnostic':'Self-assessment','Prendre rendez-vous':'Book a meeting',
    'Gouvernance · Risque · Conformité':'Governance · Risk · Compliance','Conseil, audit & formation':'Consulting, audit & training','en cybersécurité pour':'in cybersecurity for','organisations exigeantes':'demanding organizations',
    'J’accompagne DSI, RSSI, chefs de projet et organisations dans la sécurisation de leurs systèmes et leur mise en conformité — RGPD, NIS2, DORA, AI Act — avec une méthode agile et pédagogique.':'I help CIOs, CISOs, project managers and organizations secure their systems and achieve compliance — GDPR, NIS2, DORA and the AI Act — through an agile and educational approach.',
    'Ouvrir un dossier':'Open a case','Consulter les services':'View services','CONFIDENTIEL':'CONFIDENTIAL','GRC & CYBERSÉCURITÉ':'GRC & CYBERSECURITY','DOSSIER N° TW–2026 · PARIS':'FILE No. TW–2026 · PARIS',
    'Présentation':'Profile','À propos du dossier':'About this practice',
    'Consultant en gouvernance, risque et conformité (GRC), formateur en cybersécurité et consultant digital, j’accompagne depuis plusieurs années des organisations publiques et privées dans le renforcement de leur posture de sécurité et leur mise en conformité réglementaire.':'As a Governance, Risk and Compliance consultant, cybersecurity trainer and digital consultant, I have supported public and private organizations for several years in strengthening their security posture and regulatory compliance.',
    'J’interviens également comme enseignant dans des programmes Master et MBA (gouvernance, audit, cybersécurité) — une pédagogie exigeante et concrète que l’on retrouve dans chaque accompagnement. Mon approche combine rigueur méthodologique, agilité opérationnelle et transmission des compétences, afin que la cybersécurité devienne un véritable atout stratégique pour votre organisation.':'I also teach in Master’s and MBA programs covering governance, audit and cybersecurity. This demanding, practical approach shapes every engagement. I combine methodological rigor, operational agility and knowledge transfer so cybersecurity becomes a strategic asset for your organization.',
    'Satisfaction clientèle':'Client satisfaction','Chaque organisation est unique ; les solutions apportées sont personnalisées et adaptées à vos enjeux spécifiques.':'Every organization is unique; solutions are tailored to your specific challenges.',
    'Collaboration active':'Active collaboration','Votre stratégie de cybersécurité se construit ensemble, pour une mise en œuvre efficace et durable.':'We build your cybersecurity strategy together for effective and sustainable implementation.',
    'Transmission des connaissances':'Knowledge transfer','Montée en compétences des équipes, pour que la cybersécurité devienne un atout interne.':'Building team capabilities so cybersecurity becomes an internal asset.',
    'Agilité & flexibilité':'Agility & flexibility','Une gestion de projet en mode agile, qui avance par étapes vers des résultats concrets et mesurables.':'Agile project management that advances step by step toward concrete, measurable results.',
    'Services':'Services','Cinq dossiers, une méthode':'Five services, one method','Chaque dossier se consulte indépendamment. Cliquez sur un intitulé pour l’ouvrir et voir le détail de l’accompagnement proposé.':'Each service can be reviewed independently. Select a title to view the proposed support in detail.',
    'Audit & recommandations cybersécurité':'Cybersecurity audit & recommendations','RÉF. MÉTHODE — 6 AXES D’AUDIT':'METHOD REF. — 6 AUDIT AREAS','Consulter':'View',
    'Pour toute entité publique, association ou entreprise souhaitant initier une démarche de sécurisation informatique : un accompagnement personnalisé structuré autour d’un audit de pré-diagnostic, pour identifier vos points forts et vos axes d’amélioration prioritaires.':'For public bodies, non-profits and companies beginning a security program: tailored support structured around a preliminary audit to identify strengths and priority improvements.',
    'Gouvernance':'Governance','— structuration et pilotage de votre stratégie de cybersécurité.':'— structuring and steering your cybersecurity strategy.','Sécurité des accès':'Access security','— protection des identifiants et des systèmes d’authentification.':'— protecting credentials and authentication systems.','Sécurité des postes':'Endpoint security','— renforcement de la protection des équipements et logiciels.':'— strengthening device and software protection.','Infrastructures & données':'Infrastructure & data','— prévention des risques liés aux réseaux et informations sensibles.':'— preventing risks affecting networks and sensitive information.','Sensibilisation des utilisateurs':'User awareness','— formation et bonnes pratiques pour limiter les risques humains.':'— training and good practices to reduce human risk.','Réaction aux cyberattaques':'Cyberattack response','— anticipation et gestion des incidents pour une meilleure résilience.':'— anticipating and managing incidents for greater resilience.',
    'Livrable':'Deliverables','Un indicateur de maturité pour chaque thématique':'A maturity indicator for each area','Une liste de six mesures prioritaires':'A list of six priority measures','Des ressources complémentaires adaptées à vos enjeux':'Additional resources tailored to your needs',
    'Mise en conformité RGPD':'GDPR compliance','RÈGL. (UE) 2016/679':'REG. (EU) 2016/679','La protection des données personnelles est un enjeu majeur pour toute organisation. Un non-respect du règlement peut entraîner des sanctions financières significatives et nuire durablement à votre réputation.':'Personal data protection is a major issue for every organization. Non-compliance may lead to significant financial penalties and lasting reputational damage.',
    'Audit de conformité':'Compliance audit','— identification des écarts et des actions prioritaires.':'— identifying gaps and priority actions.','Mesures obligatoires':'Mandatory measures','— registre des traitements, mentions légales, politique de confidentialité.':'— processing register, legal notice and privacy policy.','Sensibilisation des équipes':'Team awareness','— bonnes pratiques et responsabilisation des collaborateurs.':'— good practices and employee accountability.','Sécurisation des données':'Data security','— protection contre les violations et cyberattaques.':'— protection against breaches and cyberattacks.','Pourquoi agir maintenant':'Why act now','Éviter les amendes et renforcer la confiance de vos clients':'Avoid fines and strengthen customer trust','Protéger votre entreprise contre les risques juridiques et informatiques':'Protect your organization against legal and IT risks','Bénéficier d’un accompagnement sur mesure':'Receive tailored support',
    'Mise en conformité NIS2':'NIS2 compliance','DIR. (UE) 2022/2555':'DIR. (EU) 2022/2555','La directive NIS2 impose de nouvelles obligations aux entreprises et organisations pour améliorer leur résilience face aux cybermenaces. Anticiper cette mise en conformité permet d’éviter les risques plutôt que de les subir.':'The NIS2 Directive introduces new obligations to improve organizational resilience against cyber threats. Preparing early helps prevent risks rather than suffer their consequences.','Audit de conformité NIS2':'NIS2 compliance audit','— évaluation des écarts et des actions à mener.':'— assessing gaps and required actions.','Renforcement de la cybersécurité':'Cybersecurity strengthening','— protection des infrastructures critiques et des données.':'— protecting critical infrastructure and data.','Obligations légales':'Legal obligations','— gouvernance, gestion des risques, plan de réponse aux incidents.':'— governance, risk management and incident response planning.','Sensibilisation & formation':'Awareness & training','— implication des équipes pour une sécurité durable.':'— involving teams for lasting security.','Pourquoi agir dès maintenant':'Why act now','Éviter les sanctions et assurer votre conformité réglementaire':'Avoid penalties and achieve regulatory compliance','Renforcer la résilience face aux cyberattaques':'Strengthen resilience against cyberattacks','Gagner en crédibilité auprès de vos clients et partenaires':'Build credibility with clients and partners',
    'Résilience numérique — DORA':'Digital operational resilience — DORA','Le règlement DORA impose aux acteurs du secteur financier de renforcer leur résilience face aux cybermenaces et aux incidents opérationnels. Anticiper cette mise en conformité, c’est transformer une contrainte réglementaire en avantage stratégique.':'DORA requires financial-sector entities to strengthen resilience against cyber threats and operational incidents. Preparing early turns a regulatory constraint into a strategic advantage.','— évaluation de votre maturité et des écarts à combler.':'— assessing maturity and gaps to address.','— protection des systèmes, gestion des risques, surveillance continue.':'— system protection, risk management and continuous monitoring.','Plan de gestion des incidents':'Incident management plan','— processus robustes et réponse efficace aux crises.':'— robust processes and effective crisis response.','Conformité avec les tiers':'Third-party compliance','— sécurisation des relations avec vos prestataires numériques.':'— securing relationships with digital service providers.','Éviter les sanctions et garantir votre conformité réglementaire':'Avoid penalties and ensure regulatory compliance','Protéger vos systèmes et données contre les cyberattaques':'Protect systems and data against cyberattacks','Renforcer la confiance de vos clients, partenaires et régulateurs':'Strengthen trust with clients, partners and regulators',
    'Formation Agile — SCRUM, Lean Startup & Kanban':'Agile training — SCRUM, Lean Startup & Kanban','MÉTHODE — SCRUM / LEAN / KANBAN':'METHOD — SCRUM / LEAN / KANBAN','Dans un environnement où les cybermenaces évoluent sans cesse, les méthodes agiles sont des atouts essentiels pour piloter vos projets de cybersécurité. Que vous soyez DSI, RSSI, chef de projet ou consultant, adoptez des pratiques éprouvées pour réagir rapidement aux incidents.':'In a constantly changing threat environment, agile methods are essential for managing cybersecurity projects. CIOs, CISOs, project managers and consultants can use proven practices to respond quickly to incidents.','— structurer vos projets cybersécurité avec des sprints courts et une gestion efficace des priorités.':'— structure cybersecurity projects through short sprints and effective prioritization.','— tester rapidement vos stratégies de protection et ajuster votre approche selon les risques réels.':'— quickly test protection strategies and adapt them to actual risks.','— visualiser le cycle de vie des menaces et fluidifier la gestion des incidents.':'— visualize the threat lifecycle and streamline incident management.','Pourquoi suivre cette formation':'Why take this training','Accélérer vos projets grâce à une approche itérative et flexible':'Accelerate projects through an iterative, flexible approach','Améliorer la coordination entre équipes IT et sécurité':'Improve coordination between IT and security teams',
    'Auto-diagnostic express':'Express self-assessment','Où en est votre organisation ?':'How mature is your organization?','Neuf axes et soixante-six critères pour une première estimation de votre niveau de maturité en cybersécurité. L’axe IA intègre les recommandations du bulletin CERTFR-2026-ACT-016. Indicatif — un audit complet affine ce résultat.':'Nine areas and sixty-six criteria provide an initial estimate of cybersecurity maturity. The AI area includes the recommendations of CERTFR-2026-ACT-016. This is indicative; a full audit refines the result.',
    'Votre gouvernance cybersécurité est-elle formalisée (rôles, responsabilités, politique écrite) ?':'Is your cybersecurity governance formalized through written roles, responsibilities and policies?','Validez séparément chaque élément réellement en place :':'Confirm each element that is actually in place:','Politique de sécurité écrite et validée':'Written and approved security policy','Responsable identifié : RSSI, DSI ou référent':'Identified CISO, CIO or security lead','Rôles et responsabilités clairement répartis':'Clearly assigned roles and responsibilities','Cartographie des risques tenue à jour':'Up-to-date risk map','Indicateurs de suivi définis':'Defined monitoring indicators','Revue régulière avec la direction':'Regular management review',
    'L’authentification renforcée (MFA) est-elle déployée sur vos accès sensibles ?':'Is multi-factor authentication deployed for sensitive access?','Le MFA ajoute une seconde preuve après le mot de passe. Validez les protections actives :':'MFA adds a second factor after the password. Confirm the active protections:','Application mobile d’authentification':'Mobile authenticator application','Validation sécurisée dans le navigateur':'Secure browser-based validation','Clé physique ou clé d’accès (passkey)':'Hardware key or passkey','Biométrie sur les appareils compatibles':'Biometrics on compatible devices','Messagerie, VPN et cloud protégés':'Protected email, VPN and cloud services','Comptes administrateurs protégés en priorité':'Administrator accounts protected as a priority',
    'Vos postes et logiciels sont-ils maintenus à jour de façon systématique ?':'Are endpoints and software systematically kept up to date?','Validez séparément chaque pratique appliquée :':'Confirm each practice that is applied:','Mises à jour automatiques des ordinateurs':'Automatic computer updates','Smartphones et tablettes maintenus à jour':'Up-to-date smartphones and tablets','Serveurs et équipements réseau corrigés':'Patched servers and network devices','Navigateurs et applications mis à jour':'Updated browsers and applications','Logiciels non supportés remplacés':'Unsupported software replaced','Correctifs critiques traités en priorité':'Critical patches prioritized',
    'Vos sauvegardes sont-elles testées régulièrement (restauration vérifiée) ?':'Are backups regularly tested through verified restoration?','Sauvegarder ne suffit pas : il faut réussir à restaurer. Validez vos garanties :':'Backing up is not enough: restoration must work. Confirm your safeguards:','Trois copies des données disponibles':'Three copies of data available','Deux supports ou environnements distincts':'Two distinct media or environments','Une copie hors ligne ou externalisée':'One offline or off-site copy','Sauvegardes chiffrées et droits séparés':'Encrypted backups and separated privileges','Erreurs de sauvegarde surveillées':'Backup errors monitored','Restauration testée et délais vérifiés':'Restoration tested and recovery times verified',
    'Vos équipes bénéficient-elles d’une sensibilisation régulière aux risques cyber ?':'Do teams receive regular cybersecurity awareness training?','Validez séparément les actions réellement organisées :':'Confirm the activities actually delivered:','Sensibilisation lors de l’arrivée':'Awareness training during onboarding','Formation renouvelée au moins chaque année':'Training renewed at least annually','Rappels courts diffusés régulièrement':'Regular short reminders','Exercices d’hameçonnage réalisés':'Phishing simulations performed','Procédure de signalement connue':'Known reporting procedure','Contenus adaptés aux fonctions exposées':'Content tailored to exposed roles',
    'Votre organisation est-elle préparée à détecter et gérer un incident de cybersécurité ?':'Is your organization prepared to detect and manage a cybersecurity incident?','Validez séparément les capacités réellement opérationnelles :':'Confirm each genuinely operational capability:','Procédure de réponse aux incidents documentée':'Documented incident response procedure','Canal d’alerte connu des équipes':'Alert channel known to teams','Responsables et cellule de crise identifiés':'Identified leaders and crisis team','Journalisation et détection surveillées':'Monitored logging and detection','Exercices de crise réalisés':'Crisis exercises performed','Retour d’expérience après incident':'Post-incident lessons learned',
    'Les risques liés à vos prestataires et fournisseurs numériques sont-ils maîtrisés ?':'Are risks from digital suppliers and service providers controlled?','Validez les mesures appliquées à votre chaîne d’approvisionnement :':'Confirm the measures applied to your supply chain:','Prestataires critiques identifiés':'Critical providers identified','Évaluation sécurité avant contractualisation':'Security assessment before contracting','Clauses de sécurité et de notification prévues':'Security and notification clauses included','Accès des prestataires limités et revus':'Provider access limited and reviewed','Preuves de conformité demandées':'Compliance evidence requested','Plan de sortie ou de réversibilité prévu':'Exit or reversibility plan established',
    'Vos actifs numériques et vos données sensibles sont-ils identifiés et classifiés ?':'Are digital assets and sensitive data identified and classified?','Validez les fondations de connaissance et de protection :':'Confirm the foundations for knowledge and protection:','Inventaire matériel tenu à jour':'Up-to-date hardware inventory','Inventaire des logiciels et services cloud':'Software and cloud service inventory','Données sensibles identifiées et classifiées':'Sensitive data identified and classified','Propriétaires des actifs désignés':'Asset owners appointed','Droits d’accès revus périodiquement':'Access rights periodically reviewed','Durées de conservation et suppression définies':'Defined retention and deletion periods',
    'Votre organisation connaît-elle, encadre-t-elle et sécurise-t-elle réellement les usages de l’intelligence artificielle, notamment agentique ?':'Does your organization understand, govern and secure its use of AI, including agentic AI?','Validez uniquement les mesures effectivement appliquées et vérifiables :':'Confirm only measures that are implemented and verifiable:','A · Gouvernance et usages de l’IA':'A · AI governance and use','Outils, modèles et usages de l’IA recensés':'AI tools, models and uses inventoried','Politique d’utilisation de l’IA formalisée':'Formal AI use policy','Données sensibles interdites ou protégées':'Sensitive data prohibited or protected','Validation humaine des résultats importants':'Human validation of material outputs','Risques, biais et conformité AI Act évalués':'Risks, bias and AI Act compliance assessed','Collaborateurs formés aux usages responsables':'Employees trained in responsible use','B · Sécurité des agents IA autonomes · CERT-FR':'B · Autonomous AI agent security · CERT-FR','Agents IA installés sur postes et mobiles recensés':'AI agents on endpoints and mobile devices inventoried','Outils non validés par la DSI ou le RSSI bloqués':'Tools not approved by the CIO or CISO blocked','Agents IA non éprouvés interdits en production':'Unproven AI agents prohibited in production','Tests réalisés en bac à sable sans données sensibles':'Tests performed in a sandbox without sensitive data','Plugins, extensions, outils et commandes contrôlés par liste blanche':'Plugins, extensions, tools and commands controlled by allowlists','Permissions et accès limités au strict nécessaire':'Permissions and access restricted to the minimum necessary','Mots de passe, clés API et secrets jamais transmis aux agents':'Passwords, API keys and secrets never shared with agents','Approbation humaine obligatoire avant toute action sensible':'Mandatory human approval before any sensitive action','Canaux, groupes et interlocuteurs autorisés limités par liste blanche':'Authorized channels, groups and users restricted by allowlist','Actions des agents journalisées, surveillées et auditables':'Agent actions logged, monitored and auditable','Injections de prompt et exfiltrations testées':'Prompt injection and exfiltration tested','Procédure d’arrêt et de révocation immédiate des accès':'Immediate shutdown and access revocation procedure','Référence :':'Reference:','CERTFR-2026-ACT-016 — Vulnérabilités et risques des produits d’automatisation par IA agentique ↗':'CERTFR-2026-ACT-016 — Vulnerabilities and risks of agentic AI automation products ↗',
    'Indicateur de maturité':'Maturity indicator','Cochez les critères en place pour obtenir votre estimation.':'Select the implemented criteria to obtain your estimate.','Recevoir mon rapport':'Get my report','Prochaine étape':'Next step','Ouvrons votre dossier':'Let’s open your case','Chaque organisation avance à son rythme et selon ses priorités. Que vous souhaitiez démarrer par un audit, une mise en conformité ciblée ou une formation pour vos équipes, je vous propose un premier échange pour construire ensemble une feuille de route adaptée.':'Every organization progresses at its own pace and according to its priorities. Whether you begin with an audit, targeted compliance or team training, I offer an initial discussion to build a tailored roadmap together.','Sur rendez-vous uniquement · Paris':'By appointment only · Paris','Choisir un rendez-vous · 30 min':'Choose a meeting · 30 min','Sélectionnez une date et un horaire.':'Select a date and time.','Demander ce rendez-vous':'Request this meeting',
    'Rapport personnalisé':'Personalized report','Recevoir votre diagnostic':'Get your assessment','Votre rapport reprend le score global, le résultat de chaque axe, les critères à renforcer, des recommandations prioritaires et l’accompagnement proposé.':'Your report includes the overall score, results by area, criteria to strengthen, priority recommendations and proposed support.','Je souhaite être rappelé(e) au sujet de ce diagnostic et j’accepte que mes coordonnées soient utilisées à cette fin.':'I would like to be called about this assessment and agree that my contact details may be used for this purpose.','Le rapport complet sera téléchargé sur votre appareil. Un e-mail récapitulatif sera préparé dans votre messagerie ; si vous demandez un rappel, Innocent Twagirumukiza sera ajouté en copie cachée afin de recevoir la notification.':'The full report will be downloaded to your device. A summary email will be prepared in your mail application; if you request a call, Innocent Twagirumukiza will be added as a blind copy to receive the notification.','Générer mon rapport':'Generate my report','Annuler':'Cancel','Politique de confidentialité (Nouvelle fenêtre)':'Privacy policy (New window)','CGU et mentions légales (Nouvelle fenêtre)':'Terms and legal notice (New window)','TWAGIRUMUKIZA — GRC & CYBERSÉCURITÉ — DOSSIER CONSULTABLE SUR RENDEZ-VOUS':'TWAGIRUMUKIZA — GRC & CYBERSECURITY — AVAILABLE BY APPOINTMENT',
    'Comprendre ce thème +':'Understand this area +','Réduire le détail −':'Hide details −','Non':'No','Oui':'Yes'
  };
  var originals=new WeakMap();
  var walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
  var nodes=[]; while(walker.nextNode()){var n=walker.currentNode;if(n.parentElement&& !['SCRIPT','STYLE'].includes(n.parentElement.tagName)){originals.set(n,n.nodeValue);nodes.push(n);}}
  var placeholders={
    'Votre nom *':'Your name *','Votre e-mail *':'Your email *','Nom et prénom *':'Full name *','Nom de l’organisme *':'Organization name *','Adresse e-mail *':'Email address *','Téléphone (si rappel)':'Phone number (if callback)'
  };
  var themeEN={
    'Gouvernance':['Governance','Formalize the security policy, responsibilities, risk map and management oversight.'],
    'Authentification et accès':['Authentication and access','Deploy strong multi-factor authentication for sensitive, administrator, cloud, VPN and email accounts.'],
    'Mises à jour et vulnérabilités':['Updates and vulnerabilities','Centralize the inventory, automate updates and define remediation deadlines based on criticality.'],
    'Sauvegardes et continuité':['Backups and continuity','Implement the 3-2-1 rule, isolate one copy and regularly test restoration and recovery times.'],
    'Sensibilisation':['Awareness','Structure an annual program, regular reminders and exercises tailored to the most exposed roles.'],
    'Gestion des incidents':['Incident management','Formalize and exercise detection, alerting, qualification, containment and lessons-learned procedures.'],
    'Prestataires et chaîne d’approvisionnement':['Providers and supply chain','Assess supplier risks, include security requirements in contracts and monitor critical providers.'],
    'Actifs et données':['Assets and data','Maintain asset inventories, classify data, assign owners and apply controls based on sensitivity.'],
    'Usage, gouvernance et sécurité de l’IA':['AI use, governance and security','Map AI uses, formalize policy, protect data, and apply restriction, isolation, human approval, logging and revocation controls to autonomous AI agents.']
  };
  var current='fr';
  function translateNode(n,to){var raw=originals.get(n),trim=raw.trim();if(!trim)return;n.nodeValue=to==='en'&&EN[trim]?raw.replace(trim,EN[trim]):raw;}
  function apply(lang){
    current=lang;document.documentElement.lang=lang;nodes.forEach(function(n){translateNode(n,lang);});
    document.querySelectorAll('[placeholder]').forEach(function(el){if(!el.dataset.frPlaceholder)el.dataset.frPlaceholder=el.placeholder;el.placeholder=lang==='en'?(placeholders[el.dataset.frPlaceholder]||el.dataset.frPlaceholder):el.dataset.frPlaceholder;});
    document.querySelectorAll('.criterion-toggle').forEach(function(b){b.textContent=lang==='en'?(b.getAttribute('aria-pressed')==='true'?'Yes':'No'):(b.getAttribute('aria-pressed')==='true'?'Oui':'Non');});
    document.querySelectorAll('.diag-item[data-theme]').forEach(function(item){if(!item.dataset.frTheme){item.dataset.frTheme=item.dataset.theme;item.dataset.frRecommendation=item.dataset.recommendation;}var tr=themeEN[item.dataset.frTheme];item.dataset.theme=lang==='en'&&tr?tr[0]:item.dataset.frTheme;item.dataset.recommendation=lang==='en'&&tr?tr[1]:item.dataset.frRecommendation;});
    document.querySelectorAll('.diag-detail-btn').forEach(function(b){var open=b.getAttribute('aria-expanded')==='true';b.textContent=lang==='en'?(open?'Hide details −':'Understand this area +'):(open?'Réduire le détail −':'Comprendre ce thème +');});
    document.querySelectorAll('.date-slot[data-iso]').forEach(function(b){var d=new Date(b.dataset.iso);b.textContent=new Intl.DateTimeFormat(lang==='en'?'en-GB':'fr-FR',{weekday:'short',day:'2-digit',month:'short'}).format(d);if(b.classList.contains('selected'))window.chosenDate=new Intl.DateTimeFormat(lang==='en'?'en-GB':'fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d);});
    if(typeof window.updateBookingStatus==='function')window.updateBookingStatus();
    var langBtn=document.getElementById('langToggle');langBtn.textContent=lang==='en'?'FR':'EN';langBtn.setAttribute('aria-label',lang==='en'?'Switch to French':'Passer en anglais');
    document.querySelectorAll('.footer-links a')[0].href=lang==='en'?'privacy-en.html':'politique-confidentialite.html';
    document.querySelectorAll('.footer-links a')[1].href=lang==='en'?'legal-en.html':'cgu-mentions-legales.html';
    document.title=lang==='en'?'Twagirumukiza — GRC & Cybersecurity':'Twagirumukiza — Dossier GRC & Cybersécurité';
    localStorage.setItem('tw-lang',lang);window.currentLanguage=lang;
  }
  document.getElementById('langToggle').addEventListener('click',function(){apply(current==='fr'?'en':'fr');});
  var theme=localStorage.getItem('tw-theme')||'dark';
  function applyTheme(t){theme=t;document.body.classList.toggle('light',t==='light');var b=document.getElementById('themeToggle');b.textContent=t==='light'?'☾':'☀︎';b.setAttribute('aria-label',t==='light'?(current==='en'?'Enable dark theme':'Activer le thème sombre'):(current==='en'?'Enable light theme':'Activer le thème clair'));localStorage.setItem('tw-theme',t);}
  document.getElementById('themeToggle').addEventListener('click',function(){applyTheme(theme==='dark'?'light':'dark');});
  applyTheme(theme);apply(localStorage.getItem('tw-lang')||'fr');
  window.applySiteLanguage=apply;
})();
